### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by yogesh-78** [sepidehamiri/pet_seg_unet#1]
Respected mam 

                     Kindly tell  me which platform you have used to execute this [rl-medical](https://github.com/amiralansary/rl-medical).

regards

**Comment by sepidehamiri** [comment]
Linux 5.4.0-146-generic Ubuntu
NVIDIA-SMI 470.161.03
CUDA Version: 11.4
PyCharm 2022.3.3
Python 3.7

**Comment by yogesh-78** [comment]
Thanks,

       I want to ask one thing can we run this code in google colab.

**Comment by sepidehamiri** [comment]
When I try to open the page in collab by extension, this error is displayed: "Current page is not recognized as a github-hosted notebook", but I think you can do it yourself.

**Comment by yogesh-78** [comment]
Thank you for your reply.

**Comment by sepidehamiri** [comment]
You're welcome, I hope I have helped.

**Comment by yogesh-78** [comment]
Greetings of the day

           Please share your email id.


Regards
